### ISSUE TITLE
Balloon topic "vibrates" when scrolling to the bottom

### ISSUE THREAD

**Issue by steph643** [sylque/discpage#27]
How to replicate:
- Open a long topic of a balloon
- Scroll all the way to the bottom -> somewhere near the bottom, the topic will start switching at high speed between 2 scroll positions.

**Comment by sylque** [comment]
This is a new issue due to the new IntersectionObserver code in Discourse: the issue comes to the fact that the topic progress bar switches back and forth between the docked and undocked state (see [here](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/components/topic-progress.js#L162)).

**Comment by sylque** [comment]
Maybe this is due to the fact that the IntersectionObserver "rootMargin" argument is wrong given the reduced width of the topic window in Discpage. See [here](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/components/topic-progress.js#L142).

**Comment by sylque** [comment]
Fixed in 1.0.48 (simple CSS change).
